version: "3"
services:
  hmpps-assess-risks-and-needs-handover-service:
    build:
      context: .
    network_mode: "host"
    container_name: hmpps-assess-risks-and-needs-handover-service
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=local
  redis:
    image: "bitnami/redis:7.0.11"
    container_name: handover-service-redis-dev
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

networks:
  hmpps:
