version: "3"
services:
  hmpps-handover-service:
    build:
      context: .
    network_mode: "host"
    container_name: hmpps-handover-service
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

networks:
  hmpps:
