version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@8

parameters:
  alerts-slack-channel:
    type: string
    default: "hmpps-assessments-notifications"
#  releases-slack-channel:
#    type: string
#    default:
  deploy:
    description: Trigger a manual deployment
    type: string
    default: ""

jobs:
  validate:
    executor: java
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

workflows:
  version: 2
  build-test-and-deploy:
    when:
      not: << pipeline.parameters.deploy >>
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_multiplatform_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          jira_update: true
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - build_docker
            - helm_lint
          helm_timeout: 5m

  deploy-to-test-env:
    when:
      and:
        - equal: [ "test", << pipeline.parameters.deploy >> ]
    jobs:
      - hmpps/build_docker:
          name: build_docker
          jira_update: true
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
          context:
            - hmpps-common-vars
            - hmpps-assess-risks-and-needs-handover-service-test
      - hmpps/deploy_env:
          name: deploy_test
          env: "test"
          jira_update: true
          jira_env_type: testing
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
          context:
            - hmpps-common-vars
            - hmpps-assess-risks-and-needs-handover-service-test
          requires:
            - build_docker
          helm_timeout: 5m

#      - request-preprod-approval:
#          type: approval
#          requires:
#            - deploy_dev
#      - hmpps/deploy_env:
#          name: deploy_preprod
#          env: "preprod"
#          jira_update: true
#          jira_env_type: staging
#          pipeline_id: <<pipeline.id>>
#          pipeline_number: <<pipeline.number>>
#          context:
#            - hmpps-common-vars
#            - hmpps-assess-risks-and-needs-handover-service-preprod
#          requires:
#            - request-preprod-approval
#          helm_timeout: 5m
#      - request-prod-approval:
#          type: approval
#          requires:
#            - deploy_preprod
#      - hmpps/deploy_env:
#          name: deploy_prod
#          env: "prod"
#          jira_update: true
#          jira_env_type: production
#          pipeline_id: <<pipeline.id>>
#          pipeline_number: <<pipeline.number>>
#          slack_notification: true
#          slack_channel_name: << pipeline.parameters.releases-slack-channel >>
#          context:
#            - hmpps-common-vars
#            - hmpps-assess-risks-and-needs-handover-service-prod
#          requires:
#            - request-prod-approval
#          helm_timeout: 5m

  security:
    triggers:
      - schedule:
          cron: "15 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          cache_key: "v2_0"
          jdk_tag: "21.0"
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars
  security-weekly:
    triggers:
      - schedule:
          cron: "0 5 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars

executors:
  java:
    docker:
      - image: cimg/openjdk:21.0
        environment:
          _JAVA_OPTIONS: -Xmx1024m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2
            -XX:ParallelGCThreads=2
            -Djava.util.concurrent.ForkJoinPool.common.parallelism=2
            -Dorg.gradle.daemon=false
      - image: cimg/redis:7.2
        environment:
          ALLOW_EMPTY_PASSWORD: yes