services:
  redis:
    ports:
      - "6379:6379"

  postgres:
    ports:
      - "5432:5432"

  hmpps-auth:
    ports:
      - "9090:9090"

  coordinator-api:
    ports:
      - "8070:8080"

  san-api:
    ports:
      - "8080:8080"

  san-ui:
    ports:
      - "3000:3000"

  arns-handover:
    image: ghcr.io/ministryofjustice/hmpps-assess-risks-and-needs-handover-service:local
    build:
      target: development
    command: gradle --parallel --build-cache --configuration-cache bootRun
    ports:
      - "7070:7070"
      - "5007:5005"
    volumes:
      - ..:/app
      - ../.gradle:/home/gradle/.gradle

  oasys-ui:
    ports:
      - "7072:3000"

volumes:
  .gradle:
  build:
