services:
  redis:
    image: redis:7.2
    networks:
      - hmpps
    environment:
      ALLOW_EMPTY_PASSWORD: yes

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:2024-10-02.25761.db2ce3c
    networks:
      - hmpps
    healthcheck:
      test: ["CMD", "curl", "-f", "http://hmpps-auth:9090/auth/health"]
      interval: 5s
      retries: 60
    environment:
      SERVER_PORT: 9090
      SPRING_PROFILES_ACTIVE: dev
      APPLICATION_AUTHENTICATION_UI_ALLOWLIST: 0.0.0.0/0
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG

  postgres:
    image: postgres:16
    networks:
      - hmpps
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    tmpfs:
      - /var/lib/postgresql

  coordinator-api:
    image: ghcr.io/ministryofjustice/hmpps-assess-risks-and-needs-coordinator-api:latest
    networks:
      - hmpps
    depends_on:
      - postgres
      - hmpps-auth
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://coordinator-api:8080/health/ping" ]
      interval: 5s
      retries: 60
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: postgres
      APP_DB_ENDPOINT: postgres:5432
      APP_DB_NAME: postgres
      APP_DB_USERNAME: root
      APP_DB_PASSWORD: dev
      HMPPS_AUTH_BASE_URL: http://hmpps-auth:9090/auth
      SAN_API_BASE_URL: http://san-api:8080
      SP_API_BASE_URL: http://sp-api:8080
      CLIENT_ID: hmpps-assess-risks-and-needs-oastub-ui
      CLIENT_SECRET: clientsecret

  san-api:
    image: ghcr.io/ministryofjustice/hmpps-strengths-based-needs-assessments-api:latest
    networks:
      - hmpps
    depends_on:
      - postgres
      - hmpps-auth
      - san-ui
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://san-api:8080/health/ping" ]
      interval: 5s
      retries: 60
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: postgres
      DATABASE_ENDPOINT: postgres:5432
      OAUTH_ENDPOINT_URL: http://hmpps-auth:9090/auth
      FORM_CONFIG_BASE_URL: http://san-ui:3000/config

  san-ui:
    image: ghcr.io/ministryofjustice/hmpps-strengths-based-needs-assessments-ui:latest
    networks:
      - hmpps
    depends_on:
      - redis
      - hmpps-auth
      - oasys-ui
    healthcheck:
      test: [ "CMD", "node", "./docker/healthcheck.js" ]
      interval: 5s
      retries: 60
    environment:
      PORT: 3000
      REDIS_HOST: redis
      HMPPS_AUTH_EXTERNAL_URL: http://localhost:9090/auth
      HMPPS_AUTH_URL: http://hmpps-auth:9090/auth
      HMPPS_ARNS_HANDOVER_URL: http://arns-handover:7070
      HMPPS_ARNS_HANDOVER_EXTERNAL_URL: http://localhost:7070
      OASYS_URL: http://localhost:7072
      HANDOVER_CLIENT_ID: strengths-and-needs-assessment
      HANDOVER_CLIENT_SECRET: san-secret
      TOKEN_VERIFICATION_ENABLED: false
      TOKEN_VERIFICATION_API_URL: http://hmpps-auth:9091/verification
      API_CLIENT_SECRET: clientsecret
      SYSTEM_CLIENT_SECRET: clientsecret
      API_CLIENT_ID: hmpps-strengths-and-needs-ui
      SYSTEM_CLIENT_ID: hmpps-strengths-and-needs-ui-client
      SESSION_SECRET: sessionsecret
      SBNA_API_URL: http://san-api:8080
      INGRESS_URL: http://localhost:3000
      HTTPS: false
      NODE_ENV: development

  arns-handover:
    image: ghcr.io/ministryofjustice/hmpps-assess-risks-and-needs-handover-service:${APP_VERSION:-latest}
    build:
      context: ../
    networks:
      - hmpps
    depends_on:
      - redis
      - hmpps-auth
      - coordinator-api
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://arns-handover:7070/health/ping" ]
      interval: 5s
      retries: 100
    environment:
      SERVER_PORT: 7070
      REDIS_HOST: redis
      SPRING_PROFILES_ACTIVE: local
      HMPPS_HANDOVER_BASE_URL: http://arns-handover:7070
      HMPPS_HANDOVER_EXTERNAL_URL: http://localhost:7070
      HMPPS_AUTH_BASE_URL: http://hmpps-auth:9090
      OASYS_BASE_URL: http://localhost:7072
      OASYS_RETURN_URLS: http://localhost:7072
      COORDINATOR_API_BASE_URL: http://coordinator-api:8080
      SERVER_ERROR_WHITELABEL_ENABLED: true
      CLIENT_ID: hmpps-assess-risks-and-needs-oastub-ui
      CLIENT_SECRET: clientsecret
      CLIENT_SAN_SECRET: san-secret
      CLIENT_SAN_OAUTH_REDIRECT_URI: http://localhost:3000/sign-in/callback
      CLIENT_SAN_HANDOVER_REDIRECT_URI: http://localhost:3000/sign-in

  oasys-ui:
    image: ghcr.io/ministryofjustice/hmpps-assess-risks-and-needs-oastub-ui:latest
    networks:
      - hmpps
    depends_on:
      - redis
    healthcheck:
      test: [ "CMD", "node", "./docker/healthcheck.js" ]
      interval: 5s
      retries: 60
    environment:
      REDIS_ENABLED: "true"
      SYSTEM_CLIENT_SECRET: clientsecret
      SYSTEM_CLIENT_ID: hmpps-assess-risks-and-needs-oastub-ui
      SESSION_SECRET: sessionsecret
      REDIS_HOST: redis
      INGRESS_URL: http://localhost:7072
      HMPPS_AUTH_URL: http://hmpps-auth:9090/auth
      TOKEN_VERIFICATION_ENABLED: "false"
      TOKEN_VERIFICATION_API_URL: http://hmpps-auth:9091/verification
      HMPPS_ARNS_HANDOVER_URL: http://arns-handover:7070
      COORDINATOR_API_URL: "http://coordinator-api:8080"
      ENVIRONMENT_NAME: DEV
      AUDIT_ENABLED: "false"
      PRODUCT_ID: FOO

networks:
  hmpps:

