---
# Per environment values which override defaults in hmpps-assess-risks-and-needs-handover-service/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: arns-handover-service-dev.hmpps.service.justice.gov.uk
    modsecurity_enabled: false
    modsecurity_snippet: |
      SecRuleEngine DetectionOnly
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecAction "id:900000,phase:1,nolog,pass,t:none,setvar:tx.paranoia_level=2"    

  env:
    SPRING_PROFILES_ACTIVE: "dev"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

  allowlist:
    capita-dev: 51.104.16.30/31
    captia-further: 172.167.141.40/32
    neil-test: 51.155.102.238/32
    capita-developers-vms-one: 85.115.52.180/32
    capita-developers-vms-two: 85.115.52.200/29
    capita-developers-vms-three: 85.115.53.180/32
    capita-developers-vms-four: 85.115.53.200/29
    capita-developers-vms-five: 85.115.54.180/32
    capita-developers-vms-six: 85.115.54.200/29
    cymulate-app-sec-one: 54.217.50.18/32
    cymulate-app-sec-two: 52.208.202.111/32
    cymulate-app-sec-three: 52.49.144.209/32
    moj-appsec-test-ip: 80.195.27.199/32
    
    groups:
      - circleci
      - internal
      - prisons

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: 
