---
# Per environment values which override defaults in hmpps-assess-risks-and-needs-handover-service/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: arns-handover-service-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_BASE_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk"
    HMPPS_HANDOVER_BASE_URL: "https://arns-handover-service-dev.hmpps.service.justice.gov.uk"
    OASYS_BASE_URL: "https://arns-oastub-dev.hmpps.service.justice.gov.uk"
    OASYS_RETURN_URLS: "https://arns-oastub-dev.hmpps.service.justice.gov.uk,https://t2.oasys.service.justice.gov.uk"
    COORDINATOR_API_BASE_URL: "https://arns-coordinator-api-dev.hmpps.service.justice.gov.uk"
    CLIENT_SP_OAUTH_REDIRECT_URI: "https://sentence-plan-dev.hmpps.service.justice.gov.uk/sign-in/callback,https://*.sentence-plan-dev.hmpps.service.justice.gov.uk/sign-in/callback"
    CLIENT_SP_HANDOVER_REDIRECT_URI: "https://sentence-plan-dev.hmpps.service.justice.gov.uk/sign-in"
    CLIENT_SAN_OAUTH_REDIRECT_URI: "https://strengths-based-needs-assessments-dev.hmpps.service.justice.gov.uk/sign-in/callback,https://*.strengths-based-needs-assessments-dev.hmpps.service.justice.gov.uk/sign-in/callback"
    CLIENT_SAN_HANDOVER_REDIRECT_URI: "https://strengths-based-needs-assessments-dev.hmpps.service.justice.gov.uk/sign-in"

  allowlist:
    mp-nat-egress-one: 13.43.9.198/32
    mp-nat-egress-two: 13.42.163.245/32
    mp-nat-egress-three: 18.132.208.127/32    
    capita-dev: 51.104.16.30/31
    captia-further: 172.167.141.40/32
    neil-test: 51.155.102.238/32
    capita-developers-vms-one: 85.115.52.180/32
    capita-developers-vms-two: 85.115.52.200/29
    capita-developers-vms-three: 85.115.53.180/32
    capita-developers-vms-four: 85.115.53.200/29
    capita-developers-vms-five: 85.115.54.180/32
    capita-developers-vms-six: 85.115.54.200/29
    joel-app-sec-1: 100.64.10.206/32
    joel-app-sec-2: 86.134.133.78/32

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: NON_PROD_ALERTS_SEVERITY_LABEL
