---
# Per environment values which override defaults in hmpps-assess-risks-and-needs-handover-service/values.yaml

generic-service:
  ingress:
    host: hmpps-assess-risks-and-needs-handover-service.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: "prod"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_HANDOVER_BASE_URL: "https://hmpps-assess-risks-and-needs-handover-service.services.justice.gov.uk"
    HMPPS_AUTH_BASE_URL: "https://sign-in-prod.hmpps.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: 
