name: Validate

on:
  workflow_call:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Validate
        run: make dev-up lint test

      - name: Export container logs
        if: failure()
        run: make save-logs OUTPUT_LOGS_DIR=${{ runner.temp }}/docker-logs

      - name: Upload test results
        if: '!cancelled()'
        uses: actions/upload-artifact@v5
        with:
          name: test_results
          path: |
            build/test_results
            build/reports/tests
            ${{ runner.temp }}/docker-logs
